### ISSUE TITLE
add contribution.md file

### ISSUE THREAD

**Issue by jivthesh** [tharun143/Enterprise-Management-System#1]
Adding a conribution.md file helps the beginner to contribute towards open source.

**Comment by tharun143** [comment]
Well, this is the original repo and I don't want to alter the codebase. I am making replication of this repo for PClubSummerOfCode.

Participate in this contest if you are interested. 😄 

http://www.pclubsummerofcode.in/

**Comment by jivthesh** [comment]
hey, I am a beginner to opensource will I be able to join?
